### ISSUE TITLE
Typedef enums are ignored

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal_lib#19]
This example gives no output during conversion:

``` c
typedef enum MyEnum {
    MyA = 0, MyB = 1, MyC = 2
} MyEnum;
```

**Comment by BlaXpirit** [comment]
This may be just my misunderstanding. Perhaps *crystal_lib* only exports items relevant to the exported functions? In which case, that may not be such a good idea. The enums are sometimes just sets of constants.

**Comment by olbat** [comment]
I think that #37 gives an answer to your question.

**Comment by mverzilli** [comment]
I agree, closing.
