### ISSUE TITLE
Build Error undefined constant Clang::TranslationUnit

### ISSUE THREAD

**Issue by puppetpies** [crystal-lang/crystal_lib#22]
root@86ddba087d31:~/crystal_lib# make crystal_lib
crystal build src/crystal_lib.cr
Error in ./src/crystal_lib/parser.cr:12: undefined constant Clang::TranslationUnit

  @tu : Clang::TranslationUnit
        ^~~~~~~~~~~~~~~~~~~~~~

make: *** [crystal_lib] Error 1

**Comment by asterite** [comment]
Oops, the Makefile is wrong. Thanks.
