### ISSUE TITLE
undefined reference to `llvm::DIBuilder::DIBuilder(llvm::Module&)'

### ISSUE THREAD

**Issue by puppetpies** [crystal-lang/crystal_lib#23]
Any ideas i have LLVM 3.6 and Clang installed

root@86ddba087d31:~/crystal_lib# make
crystal build src/main.cr
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMNewDIBuilder':
llvm_ext.cc:(.text.LLVMNewDIBuilder+0x25): undefined reference to`llvm::DIBuilder::DIBuilder(llvm::Module&)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderCreateLexicalBlock':
llvm_ext.cc:(.text.LLVMDIBuilderCreateLexicalBlock+0x8): undefined reference to`llvm::DIBuilder::createLexicalBlock(llvm::DIDescriptor, llvm::DIFile, unsigned int, unsigned int, unsigned int)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderGetOrCreateTypeArray':
llvm_ext.cc:(.text.LLVMDIBuilderGetOrCreateTypeArray+0x5): undefined reference to`llvm::DIBuilder::getOrCreateArray(llvm::ArrayRefllvm::Value*)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderGetOrCreateArray':
llvm_ext.cc:(.text.LLVMDIBuilderGetOrCreateArray+0x5): undefined reference to`llvm::DIBuilder::getOrCreateArray(llvm::ArrayRefllvm::Value*)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderCreateSubroutineType':
llvm_ext.cc:(.text.LLVMDIBuilderCreateSubroutineType+0x7): undefined reference to`llvm::DIBuilder::createSubroutineType(llvm::DIFile, llvm::DIArray, unsigned int)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderCreateLocalVariable':
llvm_ext.cc:(.text.LLVMDIBuilderCreateLocalVariable+0x59): undefined reference to`llvm::DIRefllvm::DIType::DIRef(llvm::Value const_)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderInsertDeclareAtEnd':
llvm_ext.cc:(.text.LLVMDIBuilderInsertDeclareAtEnd+0x8): undefined reference to`llvm::DIBuilder::insertDeclare(llvm::Value_, llvm::DIVariable, llvm::BasicBlock_)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderCreateEnumerationType':
llvm_ext.cc:(.text.LLVMDIBuilderCreateEnumerationType+0x8f): undefined reference to`llvm::DIBuilder::createEnumerationType(llvm::DIDescriptor, llvm::StringRef, llvm::DIFile, unsigned int, unsigned long, unsigned long, llvm::DIArray, llvm::DIType, llvm::StringRef)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMDIBuilderCreateStructType':
llvm_ext.cc:(.text.LLVMDIBuilderCreateStructType+0xab): undefined reference to`llvm::DIBuilder::createStructType(llvm::DIDescriptor, llvm::StringRef, llvm::DIFile, unsigned int, unsigned long, unsigned long, unsigned int, llvm::DIType, llvm::DIArray, unsigned int, llvm::DIType, llvm::StringRef)'
/opt/crystal/src/llvm/ext/llvm_ext.o: In function `LLVMTemporaryMDNode':
llvm_ext.cc:(.text.LLVMTemporaryMDNode+0x7): undefined reference to`llvm::MDNode::getTemporary(llvm::LLVMContext&, llvm::ArrayRef<llvm::Value_>)'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/root/crystal_lib/main" "${@}"  -rdynamic  -lz -lssl -lcrypto /opt/crystal/src/llvm/ext/llvm_ext.o`(llvm-config-3.6 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config-3.5 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config --libs --system-libs --ldflags 2>/dev/null)`-lstdc++`llvm-config-3.6 --ldflags 2>/dev/null || llvm-config-3.5 --ldflags 2>/dev/null || llvm-config --ldflags 2>/dev/null`-lclang /opt/crystal/src/ext/libcrystal.a -levent -lrt -lpcre -lm -lgc -lpthread -ldl`
make: **\* [crystal_lib] Error 1
root@86ddba087d31:~/crystal_lib# dpkg -l | grep llvm
ii  libllvm3.6:amd64                1:3.6-2ubuntu1~trusty1           amd64        Modular compiler and toolchain technologies, runtime library
ii  llvm-3.6                        1:3.6-2ubuntu1~trusty1           amd64        Modular compiler and toolchain technologies
ii  llvm-3.6-dev                    1:3.6-2ubuntu1~trusty1           amd64        Modular compiler and toolchain technologies, libraries and headers
ii  llvm-3.6-runtime                1:3.6-2ubuntu1~trusty1           amd64        Modular compiler and toolchain technologies, IR interpreter
root@86ddba087d31:~/crystal_lib# dpkg -l | grep clang
ii  libclang-3.6-dev                1:3.6-2ubuntu1~trusty1           amd64        clang library - Development package
ii  libclang-common-3.6-dev         1:3.6-2ubuntu1~trusty1           amd64        clang library - Common development package
ii  libclang1-3.6:amd64             1:3.6-2ubuntu1~trusty1           amd64        C interface to the clang library
root@86ddba087d31:~/crystal_lib# crystal --version
Crystal 0.15.0 [0f62400](Fri Apr  1 17:04:54 UTC 2016)
root@86ddba087d31:~/crystal_lib#

**Comment by puppetpies** [comment]
Just read https://github.com/crystal-lang/crystal/issues/2393 - If compiled with 0.13 Crystal it will work.

**Comment by Sija** [comment]
@puppetpies Can it be closed or is it still an issue?

**Comment by mverzilli** [comment]
I'm going to assume this is not an issue anymore. Please reopen if you still see this happening.
