### ISSUE TITLE
Does not work with Crystal 0.19.x

### ISSUE THREAD

**Issue by jeromegn** [crystal-lang/crystal_lib#29]
First I got:

```
undefined constant Crystal::StructOrUnionDef (did you mean 'Crystal::CStructOrUnionDef')
```

and once I fixed that, I got:

```
in ./src/crystal_lib/type_mapper.cr:147: undefined constant Crystal::StructDef

      klass = type.kind == :struct ? Crystal::StructDef : Crystal::UnionDef
```

Running with:

```crystal
@[Include(
  "cassandra.h"
  prefix: %w(CASS_ cass_))]
@[Link("cassandra")]
lib LibCassandra
end
```

Here's the header file for reference: [cassandra.h](https://github.com/datastax/cpp-driver/blob/72c03d601f2ba7e30b40bbdc6ad249123bb36d9f/include/cassandra.h)

**Comment by asterite** [comment]
@jeromegn Thanks! I had the changes on my machine and forgot to push them after the release.

**Comment by jeromegn** [comment]
Thanks for the quick resolution!
