### ISSUE TITLE
crystal specs do not pass

### ISSUE THREAD

**Issue by Bew78LesellB** [crystal-lang/crystal_lib#33]
With `Crystal 0.20.1 (2016-12-06)` I get

`..........EE..E.EEE..E....F.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE`
```
Finished in 543.53 milliseconds
74 examples, 1 failures, 53 errors, 0 pending
```
I didn't tried with older crystal version, I just discovered this tool and tried to use it !

I also get a lot of `/usr/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found`, I'm on : 
```
Linux BB-8 4.8.12-3-ARCH
```

Thanks

**Comment by danny8376** [comment]
stddef.h is a header file provided by compiler, try something like $export C_INCLUDE_PATH=/usr/lib/clang/3.9.1/include (for Arch with clang 3.9.1)

**Comment by mverzilli** [comment]
Closing, if you still couldn't figure it out feel free to comment.
