### ISSUE TITLE
default_target-related compilation issue with Crystal 0.28

### ISSUE THREAD

**Issue by olbat** [crystal-lang/crystal_lib#58]
The lib does not compile anymore with Crystal 0.28 (more details, see https://github.com/olbat/libgen/issues/33):
```
...

in lib/crystal_lib/src/clang.cr:1: while requiring "./clang/*"

require "./clang/*"
^

in lib/crystal_lib/src/clang/index.cr:2: while requiring "compiler/crystal/config"

require "compiler/crystal/config"
^

in /usr/lib/crystal/compiler/crystal/config.cr:37: undefined constant Crystal::Codegen::Target

    @@default_target : Crystal::Codegen::Target?
```

The issue seems to be present with every LLVM versions and platforms I've tested (see
https://travis-ci.org/olbat/libgen/builds/523117414) _[the macOS builds did not fail because they were still using Crystal 0.27]_.

I suspect https://github.com/crystal-lang/crystal/pull/7282 to be related to this issue, I'm still trying to find out how.

**Comment by RX14** [comment]
It's just a require order issue.

**Comment by bcardiff** [comment]
FYI I run `crystal spec` on this repo when doing the `test-ecosystem` in Linux and OSX platform and I notice no issues so far.

**Comment by olbat** [comment]
Oh right, sorry for the false alert @bcardiff 😳

I think you're right @RX14 :)

Still, I'm not sure how to fix this...
I tried to add an import to `compiler/crystal/**` a few days ago [but it did not work](https://travis-ci.org/olbat/libgen/builds/523174211).
If you have an idea about how to fix this, can you comment on https://github.com/olbat/libgen/issues/33? Thanks a lot!

However, since the bug is not _crystal_lib_ related so I'm closing the issue.
