### ISSUE TITLE
Compiler complains of no `LibC::Bool` type

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal_lib#78]
The type is generated here:
https://github.com/crystal-lang/crystal_lib/blob/d686bbac0fde83c31882b66ac669b8181795ab19/src/crystal_lib/type_mapper.cr#L45

This occurs on Debian Linux, not sure if `LibC::Bool` is missing for that platform in crystal or it's not something defined for any platform

**Comment by stakach** [comment]
ping @straight-shoota
would `PrimitiveType::Kind::Bool` align to something like `LibC::SizeT`

**Comment by straight-shoota** [comment]
I think there is no dedicated `bool` type in classic C. It's just `int`.
That's why `LibC::Bool` doesn't exist for any platform (only on windows there's `LibC::BOOL`).

So `PrimitiveType::Kind::Bool` should probably map to `LibC::Int`.
